/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ElCarousel: typeof import('element-plus/es')['ElCarousel']
    ElCarouselItem: typeof import('element-plus/es')['ElCarouselItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    PlayerBar: typeof import('./../components/player/PlayerBar.vue')['default']
    PlaylistSidebar: typeof import('./../components/player/PlaylistSidebar.vue')['default']
    QrCodeLogin: typeof import('./../components/QrCodeLogin.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchBar: typeof import('./../components/search/SearchBar.vue')['default']
  }
}
